language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - 5.6

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script:
  - composer install -o  --no-interaction --no-progress --prefer-dist
  - ./vendor/bin/simple-phpunit --coverage-clover=coverage.clover
